# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_label_feedsources'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedsource',
            name='url',
            field=models.URLField(default='http://localhost/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='label',
            name='url',
            field=models.URLField(default='http://localhost/'),
            preserve_default=False,
        ),
    ]
