# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_auto_20160603_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='feedSources',
        ),
    ]
