# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0008_feedsourcelabel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedsourcelabel',
            old_name='feedsource',
            new_name='feedSource',
        ),
    ]
