# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0009_auto_20160605_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='feedSources',
            field=models.ManyToManyField(through='feeds.FeedSourceLabel', to='feeds.FeedSource'),
        ),
    ]
