# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0010_label_feedsources'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
