# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0011_label_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='active',
        ),
    ]
