# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0013_feed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
